### ISSUE TITLE
UI Overhaul Minor Fixes

### ISSUE THREAD

**Issue by feeohnah** [fondfolio/admin#33]
**Important**
- [x] Clicking edit on a contribution takes me to an error, but I can edit the contribution when I refresh
- [x] When a user is directed to reset their password the password criteria are missing. Also it won’t accept a new password even when all the (mysterious) criteria are met
- [x] Reset password – new password layout is wonky, fields are too spaced out and text below title is off center
<img width="1279" alt="Screen Shot 2021-01-03 at 6 20 09 PM" src="https://user-images.githubusercontent.com/2460068/103484731-63b20400-4df1-11eb-817b-0096f9b33f32.png">

- [x] Remove the “Book“ link from the Fondfolio card dropdown on the home dashboard screen, or change it to "Order"
<img width="362" alt="Screen Shot 2021-01-03 at 6 28 29 PM" src="https://user-images.githubusercontent.com/2460068/103484752-82b09600-4df1-11eb-8566-f93b380c8a14.png">

- [x] Fields in the details tab should validate consistently. Currently Receiver name doesn't show a red border when empty, but Giver name does.
<img width="855" alt="Screen Shot 2021-01-03 at 4 08 55 PM" src="https://user-images.githubusercontent.com/2460068/103484766-9a881a00-4df1-11eb-86c3-69bce76ebf7f.png">
<img width="816" alt="Screen Shot 2021-01-03 at 4 08 47 PM" src="https://user-images.githubusercontent.com/2460068/103484767-9bb94700-4df1-11eb-83da-9f29268a6a58.png">

- [x] Order customizations — when I select a new cover color it doesn’t update in the UI, even if I refresh the page. It updates in the database.
<img width="363" alt="Screen Shot 2021-01-03 at 6 30 33 PM" src="https://user-images.githubusercontent.com/2460068/103484818-ecc93b00-4df1-11eb-96ee-3ea24b42f40c.png">
<img width="767" alt="Screen Shot 2021-01-03 at 6 30 38 PM" src="https://user-images.githubusercontent.com/2460068/103484817-eb980e00-4df1-11eb-90ad-22a890587f4a.png">

- [x] Fix spacing of Terms text on mobile Sign Up
<img width="490" alt="Screen Shot 2021-01-03 at 6 56 32 PM" src="https://user-images.githubusercontent.com/2460068/103485276-7b8b8700-4df5-11eb-8e44-b3d847712102.png">

- [x] Appzi feedback link is getting in the way in several places on mobile

- [x] Help and Fondfolio logo link in header should probably have a cursor pointer?

**Less Important**
- [x] Log In / Sign Up is not quite centered on larger mobile devices
<img width="320" alt="Screen Shot 2021-01-03 at 7 06 12 PM" src="https://user-images.githubusercontent.com/2460068/103485454-c4900b00-4df6-11eb-9fd3-1246612e1e50.png">

- [x] Maybe we shouldn't show the "order now and receive by ..." until they actually have 12 contributions and can order?
- [x] Content in contribution is not centered
- [x] How to add the url helper to a card url (for example for the "Read our share FAQ" link in the Contributions tab)?
- [x] The toasts only seem to show when something was successful, not if there’s and error, is that intentional?
- [ ] The update button being at the bottom of each tab feels super awkward. I think we should consider having it float on the right side. 
- [x] The "Select An Event” explainer box pushes the questions down too far, consider adding a Label and helper Text to the Choice list instead.
- [ ] I think drop the border around the column headers on the Orders table

**Comment by cartogram** [comment]
![image](https://user-images.githubusercontent.com/462077/103484763-95c36600-4df1-11eb-969a-ffe0eaa2106b.png)![image](https://user-images.githubusercontent.com/462077/103484768-9d830a80-4df1-11eb-9a62-a0c826a0a065.png)![image](https://user-images.githubusercontent.com/462077/103484770-9fe56480-4df1-11eb-98f9-13b43ee21f2e.png)![image](https://user-images.githubusercontent.com/462077/103484774-a247be80-4df1-11eb-9857-6ad1f4705d2a.png)![image](https://user-images.githubusercontent.com/462077/103484775-a4118200-4df1-11eb-89f2-351d802d7e2a.png)![image](https://user-images.githubusercontent.com/462077/103484779-a7a50900-4df1-11eb-842e-d991fd430251.png)![image](https://user-images.githubusercontent.com/462077/103484781-aa076300-4df1-11eb-89b4-4e8eae46bd8c.png)![image](https://user-images.githubusercontent.com/462077/103484785-ad9aea00-4df1-11eb-805a-b4eb978f5146.png)![image](https://user-images.githubusercontent.com/462077/103484786-affd4400-4df1-11eb-81ac-b0bf13f8983c.png)![image](https://user-images.githubusercontent.com/462077/103484787-b390cb00-4df1-11eb-8573-85ee7e00937c.png)![image](https://user-images.githubusercontent.com/462077/103484788-b5f32500-4df1-11eb-864a-3603dad869ee.png)![image](https://user-images.githubusercontent.com/462077/103484795-b986ac00-4df1-11eb-9cf4-4a5773133149.png)
